version: '3.6'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
      target: development
    env_file:
      - .env.local
    ports:
      - 3000:3000
    volumes:
      - .:/app
    
  openai-apiserver:
    build:
      context: .
      dockerfile: dev_components/openai_apiserver/Dockerfile
    ports:
      - 8080:80

  mongo:
    image: mongo
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_URL: mongodb://root:example@mongo:27017/
