export const AllLangs = [
  { key: 'ar', title: 'العربية' },
  { key: 'bn', title: 'বাংলা' },
  { key: 'de', title: 'Deutsch' },
  { key: 'en', title: 'English' },
  { key: 'es', title: 'Español' },
  { key: 'fr', title: 'Français' },
  { key: 'he', title: 'עִבְרִית' },
  { key: 'id', title: 'Bahasa Indonesia' },
  { key: 'it', title: 'Italiano' },
  { key: 'ja', title: '日本語' },
  { key: 'ko', title: '한국어' },
  { key: 'pl', title: 'Polski' },
  { key: 'pt', title: 'Português' },
  { key: 'ro', title: 'Română' },
  { key: 'ru', title: 'Русский' },
  { key: 'si', title: 'සිංහල' },
  { key: 'sv', title: 'Svenska' },
  { key: 'te', title: 'తెలుగు' },
  { key: 'vi', title: 'Tiếng Việt' },
  { key: 'zh', title: '简体中文' },
];
